eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
    preferIpAddress: true
    hostname: localhost
spring:
  zipkin:
    base-url: http://localhost:9411/zipkin/
  application:
    name: customerMongoDemo
  cloud:
    discovery:
      enabled: true
server:
  port: 8069
  data:
    mongodb:
      database: BankDB
      port: 27017

management:
  endpoints:
    web:
      exposure:
        include: "*"
      health:
        show-details=always:


logging:
  file:
    name: C:/Users/divyabharathic/IdeaProjects/customer/src/logs/customer_service.log
